batch_scheduler:
  batch_size_increments:
  - 128
  - 256
  - 512
  enabled: false
  schedule_epochs:
  - 10
  - 25
  - 40

data:
  data_augmentation: false
  dataset_name: MNIST

global:
  device: auto
  num_workers: 4
  report_dir: logs
  save_dir: checkpoints
  seed: 42

logging:
  log_interval_steps: 100
  project_name: Advanced-NN-Assignment-3
  reporter: wandb
  run_name: Base_ResNet18_AdamW
  
lr_scheduler:
  enabled: false
  gamma: 0.1
  name: StepLR
  step_size: 15
model:
  name: resnet18
  pretrained: false
optimizer:
  lr: 0.001
  name: SGD
  sgd_params:
    dampening: 0.0
    momentum: 0.0
    nesterov: false
  weight_decay: 0.01
training:
  batch_scheduler:
    batch_size_increments:
    - 128
    - 256
    - 512
    enabled: false
    schedule_epochs:
    - 10
    - 25
    - 40
  batch_size: 128
  early_stopping:
    enabled: false
    patience: 10
  epochs: 50
